New SSH key flow
loophole/cli pull request #63
Opened 2020-11-17 09:34 UTC by denny241

Closes #62

2020-11-19 11:36 UTC, 0x7f commented on internal/app/loophole/loophole.go
> +		bitSize := 4096
Thumbs up for 4096 bits for RAS :) What about switching to `Ed25519` already? My private keys are all RSA still, but looks like Ed25519 is recommended these days? Does our loophole infrastructure even support it?

2020-11-19 12:44 UTC, Morishiri commented on internal/app/loophole/loophole.go
> +		bitSize := 4096
Would need to check on gateway side

2020-11-19 12:56 UTC, Morishiri commented on internal/app/loophole/loophole.go
>  func parsePublicKey(file string) (ssh.AuthMethod, ssh.PublicKey, error) {
I would like to make this whole ssh topic separate `package`, becuase this one grew too much.

2020-12-03 07:40 UTC, Morishiri commented on internal/pkg/keys/keys.go
>  func ParsePublicKey(terminalState *terminal.State, file string) (ssh.AuthMethod, ssh.PublicKey, error) {
You missed changing the default file in `cmd/virtual-serve.go` line `25`. It should now be default get some files from `loophole` cache dir.

2020-12-03 07:43 UTC, Morishiri commented on internal/pkg/keys/keys.go
> +//keySavedInSSHAgent goes through the identities saved in SSH Agent and looks for a specific key. If found, it returns true and the index, otherwise false and -1.
Please split longer comments in two (or more)  lines so it's better readable

2020-12-03 07:46 UTC, Morishiri requested changes
Left 2 comments for you, but overall - great job :1st_place_medal:

2020-12-07 08:34 UTC, Morishiri approved these changes

2020-12-07 09:17 UTC, merged