Initial interactive mode
loophole/cli pull request #83
Opened 2020-12-22 09:41 UTC by denny241

Closes #64 

known issues:
hostnames are forced to lowercase for now because of an issue with the survey library

things I want to add:
- basic auth prompt
- save last used options for QoL
- move the definitions for the prompts to models(?), or at least move them somewhere else where they don't clutter the code as much
- display the equivalent command to the options the user chose

2021-01-04 07:09 UTC, Morishiri commented on cmd/root.go
> +					return errors.New("enter a valid string")
I would change the message to say "enter a valid number"

2021-01-04 07:10 UTC, Morishiri commented on cmd/root.go
> +					return errors.New("enter a valid string")
or just keep it as below: `port must be a valid number between 0-65535`

2021-01-04 07:11 UTC, Morishiri commented on cmd/root.go
> +				} else { //else is necessary here to keep access to path
this is actually not necessary (we can open a tunnel to non-existing path) and when user creates it it will be working :p but in interactive mode this check is fine I guess.

2021-01-04 07:12 UTC, Morishiri commented on cmd/root.go
> +				return fmt.Sprintf("'%s'", ans)
why do we need it in quotation marks?

2021-01-04 07:12 UTC, Morishiri commented on cmd/root.go
> +	if res == "Expose an HTTP Port" {
I would move this values to constants

2021-01-04 07:15 UTC, Morishiri commented on cmd/root.go
> +		Options: []string{"Expose an HTTP Port", "Expose a local path", "Expose a local path with WebDAV", "Logout"},
I would remove `Logout` from here

2021-01-04 07:18 UTC, denny241 commented on cmd/root.go
> +				return fmt.Sprintf("'%s'", ans)
I put the path in quotation marks to avoid issues with paths that have spaces in them

2021-01-04 07:39 UTC, Morishiri commented on cmd/root.go
> +				return fmt.Sprintf("'%s'", ans)
Okay, good point

2021-01-04 07:39 UTC, Morishiri commented on cmd/root.go
> +	if res == "Expose an HTTP Port" {
also maybe use `switch` instead of `if else`

2021-01-04 07:40 UTC, Morishiri commented on cmd/root.go
> +		os.Exit(0) //if Execute() should fail, don't ask for hostname etc. but instead exit
if it's fail it should not return `0`

2021-01-05 09:12 UTC, Morishiri requested changes

2021-01-05 09:12 UTC, Morishiri commented on cmd/root.go
> +const http = "Expose an HTTP Port"
I would rather see it as:
```
const (
    AnswerTunnelTypeHTTP = "Expose an HTTP Port"
    AnswerTunnelTypePath = "Expose a local path"
    AnswerTunnelTypeWebDav = "Expose a local path with WebDAV"
)
```

2021-01-05 09:12 UTC, Morishiri commented on cmd/root.go
> +					return errors.New("port must be between 0-65535")
Since this message is used 3 times it can be extracted to `const` as well.

2021-01-05 09:12 UTC, Morishiri commented on cmd/root.go
> +		Options: []string{"Yes", "No"},
`Yes`, `No` answers can also be const as it's used in multiple places.

2021-01-05 09:12 UTC, Morishiri commented on cmd/root.go
> +		Message: "Your last settings were: '" + lastArgs + "', would you like to reuse them?",
use `fmt.Sprintf`

2021-01-05 09:12 UTC, Morishiri commented on cmd/root.go
> +		arguments = append(arguments, "--hostname", hostname)
we should be consistent and either use `-h` here or `--basic-auth-username` below when printing the command to the user

2021-01-05 09:12 UTC, Morishiri commented on cmd/root.go
> +			Prompt: &survey.Input{Message: "Please enter the username you want to use: "}, //not asking for a password since it's already implemented in virtual-serve
but we should add a placeholder like `--password <password>` if basic auth is used to the final command displayed to the user to be 100% consistent

2021-01-05 09:12 UTC, Morishiri commented on cmd/root.go
> +				var validChars = regexp.MustCompile(`^[a-z0-9]+$`).MatchString
this should use the same regexp as API. which is `^[a-z][a-z0-9]{0,30}$`

2021-01-05 09:12 UTC, Morishiri commented on cmd/root.go
> +				if hostname, ok := val.(string); !ok || len(hostname) > 31 || len(hostname) < 6 || !validChars(hostname) || !unicode.IsLetter(rune(hostname[0])) {
`len(hostname) < 6` would break "premium" users feature `short hostname`

2021-01-05 09:12 UTC, Morishiri commented on cmd/root.go
> +	cmd := httpCmd.Root() //TODO: find a better way to access rootCMD
you can access it from here, becuase you're in the same package. Simply use `rootCmd`

2021-01-05 09:12 UTC, Morishiri commented on cmd/root.go
> +		if res == "Yes" {
`const`

2021-01-05 09:12 UTC, Morishiri commented on cmd/root.go
> +		arguments = []string{"http", strconv.Itoa(exposePort)}
`http`, `path`, `webdav` should be cost as well. Maybe we can even make them consts in the proper file where this commands are defined

2021-01-05 09:12 UTC, Morishiri commented on main.go
> +	c := closehandler.SetupCloseHandler("https://forms.gle/K9ga7FZB3deaffnV7") //needs to be here instead of root to avoid duplicates
Ok, let's keep it like this for now. I have a plan to change it a little bit anyway

2021-01-07 07:31 UTC, denny241 commented on cmd/root.go
> +	cmd := httpCmd.Root() //TODO: find a better way to access rootCMD
Already tried that, problem is that I run into the following error every time I try to use rootCmd itself:
`cmd/root.go:37:5: initialization loop:
        /home/denny/git/loophole/cli/cmd/root.go:37:5: rootCmd refers to
        /home/denny/git/loophole/cli/cmd/root.go:174:6: interactivePrompt refers to
        /home/denny/git/loophole/cli/cmd/root.go:37:5: rootCmd`

2021-01-07 07:42 UTC, Morishiri commented on cmd/root.go
> +	cmd := httpCmd.Root() //TODO: find a better way to access rootCMD
Ok, let's keep it like this then.

2021-01-07 07:43 UTC, Morishiri commented on cmd/root.go
> +	cmd := httpCmd.Root() //TODO: find a better way to access rootCMD
Or you can try declaring `rootCmd` first like
```
var rootCmd cobra.Command

rootCmd = &cobra.Command{ ... }
```

then you should be able to refer to it.

2021-03-02 10:08 UTC, Morishiri commented
Opened #109 instead

2021-03-02 10:08 UTC, closed without merging