Fix input from pipe
loophole/cli pull request #96
Opened 2021-02-01 14:55 UTC by denny241

Closes #95 
Still want to clean it up a little before we merge it and haven't had time to test it properly yet, but the first commit should everything that is needed to fix the issue.

2021-02-02 13:08 UTC, denny241 commented
Should be good now. 
I put the IsPipe() function into the closehandler package, but if you can think of a better spot to put it or if you think this is a good chance to make something like a utils pkg, let me know.

2021-02-02 19:39 UTC, 0x7f commented on cmd/virtual-serve.go
> +				communication.Warn(err.Error())
Does it make sense to continue in case we run into an error here? Or shall the program exit with some non-zero code?

2021-02-02 19:41 UTC, 0x7f commented on internal/pkg/closehandler/closehandler.go
> +			communication.Warn(err.Error())
Same here. I guess the value for `terminalState` is undefined and we should not try reading it in case there is an error.

2021-02-02 19:41 UTC, 0x7f commented on internal/pkg/closehandler/closehandler.go
> +		communication.Warn(err.Error())
Same here.

2021-02-02 19:41 UTC, 0x7f approved these changes
LGTM. I would just change the error paths and exit the program right away.

2021-02-03 06:55 UTC, Morishiri commented on cmd/virtual-serve.go
> +				communication.Warn(err.Error())
I think that's exactly what makes it work in scripts :P Because it was not able to obtain `terminalState` correctly then and we can ignore it as `terminalState` is only used to display things, am I right @denny241 ?

2021-02-03 07:01 UTC, Morishiri requested changes

2021-02-03 07:04 UTC, Morishiri commented on internal/pkg/closehandler/closehandler.go
> +	var terminalState *terminal.State
Additionally https://pkg.go.dev/golang.org/x/crypto/ssh/terminal says ```Deprecated: this package moved to golang.org/x/term.```

We should refactor it to use https://pkg.go.dev/golang.org/x/term.

2021-02-03 07:06 UTC, Morishiri commented on internal/pkg/closehandler/closehandler.go
> +	var terminalState *terminal.State
May be a separate PR.

2021-02-08 13:11 UTC, denny241 commented on internal/pkg/closehandler/closehandler.go
> +	var terminalState *terminal.State
will open a separate PR for it

2021-02-08 13:13 UTC, 0x7f approved these changes

2021-02-08 13:15 UTC, Morishiri approved these changes

2021-02-08 14:02 UTC, merged